### ISSUE TITLE
I hava a problem?

### ISSUE THREAD

**Issue by eshinesimida** [namaggarwal/facebook-location#1]
PAGE_ACCESS_TOKEN = ''
API_AI_CLIENT_ACCESS_TOKEN = ''

user = {

}
why the variable is null?

**Comment by namaggarwal** [comment]
You need to put the token that you get from facebook

**Comment by eshinesimida** [comment]
Would I need to put the user from facebook?

**Comment by eshinesimida** [comment]
Would you run a example from the code ? Thank you

**Comment by namaggarwal** [comment]
For the user, just leave it as it is. I am using it to store the location that I get from Facebook
